import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Email or Identity Number' }).click();
  await page.getByRole('textbox', { name: 'Email or Identity Number' }).fill('admin@sliit.lk');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Tournament Bracket' }).click();
  await page.getByRole('button', { name: 'Golden ralley Select →' }).click();
  await page.getByRole('textbox', { name: 'Enter team name...' }).click();
  await page.getByRole('textbox', { name: 'Enter team name...' }).fill('team 1');
  await page.getByRole('button', { name: '+ Add Team' }).click();
  await page.getByRole('textbox', { name: 'Enter team name...' }).click();
  await page.getByRole('textbox', { name: 'Enter team name...' }).fill('team 2');
  await page.getByRole('button', { name: '+ Add Team' }).click();
  await page.getByRole('textbox', { name: 'Enter team name...' }).click();
  await page.getByRole('textbox', { name: 'Enter team name...' }).fill('team 3');
  await page.getByRole('button', { name: '+ Add Team' }).click();
  await page.getByText('vsScore Match').first().click();
  await page.getByRole('spinbutton').first().click();
  await page.getByRole('spinbutton').first().fill('');
  await page.getByRole('spinbutton').first().click();
  await page.getByRole('spinbutton').first().fill('1');
  await page.getByRole('spinbutton').nth(1).click();
  await page.getByRole('spinbutton').nth(1).fill('1');
  await page.getByRole('button', { name: 'team 1' }).click();
  await page.getByRole('button', { name: 'team 1 + Point' }).click();
  await page.getByRole('button', { name: 'team 1 + Point' }).click();
  await page.getByRole('button', { name: 'team 1 + Point' }).click();
  await page.getByRole('button', { name: 'team 1 + Point' }).click();
  await page.getByRole('button', { name: 'team 1 + Point' }).dblclick();
  await page.getByRole('button', { name: 'team 1 + Point' }).click();
  await page.getByRole('spinbutton').first().click();
  await page.getByRole('button', { name: 'Tournament Bracket' }).click();
  await page.getByText('Score Match').nth(1).click();
  await page.getByRole('button', { name: 'team 1' }).click();
  await page.getByRole('button', { name: 'team 1 + Point' }).click();
  await page.getByRole('button', { name: 'team 1 + Point' }).click();
  await page.getByRole('button', { name: 'team 1 + Point' }).click();
  await page.getByRole('button', { name: 'team 1 + Point' }).click();
  await page.getByRole('button', { name: 'team 1 + Point' }).click();
  await page.getByRole('button', { name: 'team 1 + Point' }).click();
  await page.getByRole('button', { name: 'team 1 + Point' }).click();
  await page.getByRole('button', { name: 'team 1 + Point' }).click();
  await page.getByRole('button', { name: 'Tournament Bracket' }).click();
  await page.getByText('vsScore Match').nth(2).click();
  await page.getByRole('button', { name: 'team 3' }).click();
  await page.getByRole('button', { name: 'team 2 + Point' }).click();
  await page.getByRole('button', { name: 'team 2 + Point' }).dblclick();
  await page.getByRole('button', { name: 'team 2 + Point' }).click();
  await page.getByRole('button', { name: 'team 2 + Point' }).click();
  await page.getByRole('button', { name: 'team 2 + Point' }).click();
  await page.getByRole('button', { name: 'team 2 + Point' }).click();
  await page.getByRole('button', { name: 'Tournament Bracket' }).click();
  await page.getByRole('button', { name: 'Generate Summary Report' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Print / Download PDF' }).click();
  const page1 = await page1Promise;
  await page.getByRole('button', { name: '✕' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Clear Bracket' }).click();
});